#!/usr/bin/env php
<?php
require_once __DIR__ . '/../vendor/autoload.php';

use Workerman\Worker;
use PHPSocketIO\SocketIO;
use AppBundle\Server\TestServer;
// listen port 2021 for socket.io client

$io = new SocketIO(2021);
$io->on('connection', function($socket)use($io){
    $io->emit('chat message', json_encode(array('msg' =>'222222')));
    $socket->on('message', function($msg)use($io){
        $Test = new TestServer();
        $io->emit('chat message', $Test->aa());
    });
});

Worker::runAll();
